-- MySQL Script generated by MySQL Workbench
-- 12/12/14 21:09:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webline` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `webline` ;

-- -----------------------------------------------------
-- Table `webline`.`wb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webline`.`wb_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webline`.`wb_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webline`.`wb_menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NULL,
  `datahora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webline`.`wb_conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webline`.`wb_conteudo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wb_menu_id` INT NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `datahora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webline`.`wb_infoad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webline`.`wb_infoad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `rodape` MEDIUMTEXT NULL,
  `c_menu` VARCHAR(45) NOT NULL,
  `c_hover_menu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE USER 'webline' IDENTIFIED BY 'webline';

GRANT SELECT, INSERT, TRIGGER ON TABLE `webline`.* TO 'webline';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `webline`.* TO 'webline';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `webline`.`wb_usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `webline`;
INSERT INTO `webline`.`wb_usuarios` (`id`, `login`, `senha`, `email`) VALUES (1, 'administrador', 'e10adc3949ba59abbe56e057f20f883e', 'admin@site.com.br');

COMMIT;


-- -----------------------------------------------------
-- Data for table `webline`.`wb_infoad`
-- -----------------------------------------------------
START TRANSACTION;
USE `webline`;
INSERT INTO `webline`.`wb_infoad` (`id`, `email`, `telefone`, `rodape`, `c_menu`, `c_hover_menu`) VALUES (1, 'admin@user', '(99)999999999', 'All rights Reserved', '#000000', '#FFFFFF');

COMMIT;

